### ISSUE TITLE
yein mod paketi pls [çok mod Bİr arada sevenler için

### ISSUE THREAD

**Issue by uluhakan40** [kofteistkofte/M.U.Z.-Arcana#1]
PEKİ KONU SİLİNMİŞYİR

**Comment by uluhakan40** [comment]
abi öyle bir mod paketi çok istiyorum :(

**Comment by uluhakan40** [comment]
internetteki büsürü mod ben 150 tane bir araya getirdim ama :((( silmek zorunda kaldım hata verdiler dediğim hatayı

**Comment by uluhakan40** [comment]
10 12 saat uraştım keşke silmeyip internete atsaydım sen hatalarnı birkaç saatte allederdin

**Comment by kofteistkofteold** [comment]
Burası M.U.Z. Arcana'nın hata raporları için bir yer! Bir daha böyle gerizekalıca bir şey yapmadan önce birkaç kere daha düşün!!!
