### ISSUE TITLE
Yeni bir harita!

### ISSUE THREAD

**Issue by BarisMistin** [kofteistkofte/M.U.Z.-Arcana#2]
Benim gibi patatesten yaratılmış Unbreaking enchantlı wooden pc ye sahip oyuncular için biraz daha hafif bir map koyulabilir mod pack e ve bu arada evet bu bir sorun değil fakat bu github da yazdığım ilk şey ve nereye ne yapıcağımı bilemedim :+1:

**Comment by kofteistkofteold** [comment]
1.1 sürümünde isteğe bağlı modlar kısmı bayağı detaylı bir biçimde şekillendirilecek. Önerilen gene Joruney Map olacak ancak 2-3 harita modu daha eklenecek.

**Comment by kofteistkofteold** [comment]
1.1.0 sürümünde bu özellik eklendi
