### ISSUE TITLE
Chunk Loader

### ISSUE THREAD

**Issue by lartofan06** [kofteistkofte/M.U.Z.-Arcana#3]
Köfte ben chunk loader ı her kurduğumda ve oyundan çıkıp bidaha girdiğimde oyuna giremiyorum loading world de kalıyor daha sonrasında beni tekrar oyunun girişine yönlendiriyor..

**Comment by kofteistkofteold** [comment]
Daha fazla bilgi verebilir misiniz? Hata mesajı varsa ya da oyun klasöründe bir chrash log gönderebilir misiniz?

**Comment by lartofan06** [comment]
loading world diyor uzun bir süre beklkedikten sonra yine aynı single player ekranına yolluyor ordan dünyamı seçip girdigimde de loading world shutting down internal server... ve tekrar oyun ana sayfa ekranı ve bunlar 5 6 dk mı alıyor

**Comment by lartofan06** [comment]
chunk loader ın seviyesini çok arttırmam la alakalı olabilrmi acaba bilemedim

**Comment by kofteistkofteold** [comment]
Bu şey bir bug değil, yapmaman gereken bir şey. Chunk Loader'ı ihtiyaç duyduğun kadar açmalısın, aşırı yüksek bir seviyede açarsan tabii ki de gider işlemcinin çalıştıramayacağı kadar sistemini yorar.

**Comment by kofteistkofteold** [comment]
Ve bir dahakine hata bildirimlerinde düzgün bir başlık kullan.
